version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:80"
    volumes:
      - .:/project
    environment:
      - C_FORCE_ROOT=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AGENT_API_URL=http://176.108.244.85:8888  # Your working host IP
    depends_on:
      - redis
      - celery_worker

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: celery -A backend.core.celery_worker worker --loglevel=info
    environment:
      - C_FORCE_ROOT=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/project
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9002:9000"
    volumes:
      - ./input:/input
      - ./output:/output
    environment:
      - API_URL=http://backend:80/api
      - PLINK_API_URL=http://plink:5000
    depends_on:
      - backend
      - plink

  plink:
    build:
      context: .
      dockerfile: Dockerfile.plink
    ports:
      - "5000:5000"
    volumes:
      - ./input:/input
      - ./output:/output
    working_dir: /

networks:
  default:
    driver: bridge