FROM ubuntu:22.04

# Base system configuration
ENV SOFT=/soft
RUN mkdir -p ${SOFT}

# Set environment variables to suppress interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# System packages installation (single layer for base dependencies)
RUN apt-get update && apt-get install -y \
    unzip \
    gpg-agent \
    software-properties-common \
    gnupg2 \
    dirmngr \
    autoconf \
    automake \
    bzip2 \
    cmake \
    g++ \
    gcc \
    libbz2-dev \
    libcurl4-openssl-dev \
    liblzma-dev \
    libncurses-dev \
    libncurses5-dev \
    libncursesw5-dev \
    libssl-dev \
    make \
    parallel \
    wget \
    zlib1g-dev \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# libdeflate 1.23 (release date: 2024-12-16)
ENV LIBDEFLATE_VERSION=1.23
ENV LIBDEFLATE=${SOFT}/libdeflate-${LIBDEFLATE_VERSION}
ENV PATH="${LIBDEFLATE}/bin:${PATH}"

RUN wget https://github.com/ebiggers/libdeflate/archive/refs/tags/v${LIBDEFLATE_VERSION}.tar.gz \
    && tar -xzf v${LIBDEFLATE_VERSION}.tar.gz \
    && cd libdeflate-${LIBDEFLATE_VERSION} \
    && mkdir build && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX=${LIBDEFLATE} .. \
    && make -j$(nproc) \
    && make install \
    && cd ../.. \
    && rm -rf libdeflate-${LIBDEFLATE_VERSION} v${LIBDEFLATE_VERSION}.tar.gz

# -------------------------------------------------------------------
# HTSlib 1.21 (release date: 2024-09-12)
ENV HTSLIB_VERSION=1.21
ENV HTSLIB=${SOFT}/htslib-${HTSLIB_VERSION}
ENV PATH="${HTSLIB}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${HTSLIB}/lib"
ENV HTSFILE="${HTSLIB}/bin/htsfile" 

RUN wget https://github.com/samtools/htslib/releases/download/${HTSLIB_VERSION}/htslib-${HTSLIB_VERSION}.tar.bz2 \
    && tar -xjf htslib-${HTSLIB_VERSION}.tar.bz2 \
    && cd htslib-${HTSLIB_VERSION} \
    && ./configure --prefix=${HTSLIB} --enable-libcurl --with-libcurl --enable-s3 --enable-gcs \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf htslib-${HTSLIB_VERSION} htslib-${HTSLIB_VERSION}.tar.bz2

# -------------------------------------------------------------------
# BCFtools 1.21 (release date: 2024-09-12)
ENV BCFTOOLS_VERSION=1.21
ENV BCFTOOLS=${SOFT}/bcftools-${BCFTOOLS_VERSION}
ENV PATH="${BCFTOOLS}/bin:${PATH}"
ENV BCFTOOLS="${BCFTOOLS}/bin/bcftools"  

RUN wget https://github.com/samtools/bcftools/releases/download/${BCFTOOLS_VERSION}/bcftools-${BCFTOOLS_VERSION}.tar.bz2 \
    && tar -xjf bcftools-${BCFTOOLS_VERSION}.tar.bz2 \
    && cd bcftools-${BCFTOOLS_VERSION} \
    && ./configure --prefix=${SOFT}/bcftools-${BCFTOOLS_VERSION} --with-htslib=${HTSLIB} \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf bcftools-${BCFTOOLS_VERSION} bcftools-${BCFTOOLS_VERSION}.tar.bz2

# -------------------------------------------------------------------
# PLINK 2.0 alpha for Linux AVX2 AMD1 (Development) (release date: 2025-07-07)

RUN mkdir -p src \
    mkdir -p input

RUN wget https://s3.amazonaws.com/plink2-assets/alpha5/plink2_linux_x86_64_20250806.zip \
    && unzip plink2_linux_x86_64_20250806.zip

# -------------------------------------------------------------------
# PLINK 1.9 for Linux 64-bit (Stable) (release date: 2025-06-15)

RUN wget https://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20250615.zip \
    && unzip plink_linux_x86_64_20250615.zip
ENV PATH="${PATH}:/"

# Install Python 3.11 and set as default
RUN  add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get install -y --no-install-recommends \
    python3.11 \
    python3.11-dev \
    python3.11-distutils \
    python3-pip && \
    ln -sf /usr/bin/python3.11 /usr/bin/python && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install packages
RUN python -m pip install --no-cache-dir \
    pandas==2.2.3 \
    pysam==0.23.0 \
    flask==3.0.0

COPY ./src/ /src/

RUN sed -i 's/\r$//' /src/entrypoint.sh
RUN chmod u+x /src/entrypoint.sh 
RUN chmod u+x /src/plink_api.py

WORKDIR /

EXPOSE 5000

ENTRYPOINT ["python", "src/plink_api.py"]